name: Vasilis Kalligas, Software Engineer
description: The tales of a Software Engineer called Vasilis Kalligas
markdown: kramdown
author: Vasilis Kalligas

gems:
  - jekyll-sitemap

social:
  github: https://github.com/arcanoid
  email: billkall@gmail.com
  google_plus: billkall@gmail.com

personal_info:
  Sex: Male
  Military obligations: Fulfilled (February 2010 - November 2010)
  Email: billkall@gmail.com
  Phone: (+30) 69432318030
  
professional_experience:
  Lead Software Engineer:
    from: March 2016
    until: now
    company: e-Travel S.A.
  Team Leader for Front-end Team:
    from: February 2013
    until: March 2016
    company: e-Travel S.A.
  Web Developer:
    from: Novembrer 2011
    until: February 2013
    company: e-Travel S.A.
  Full-stack Software Engineer:
    from: March 2011
    until: November 2011
    company: CMS
  Software Engineer:
    from: January 2011
    until: March 2011
    company: Wap5 Telecommunications Ltd.
  ECDL Instructor:
    from: January 2008
    until: December 2009
    company: Technoplus
  ECDL Instructor:
    from: October 2007
    until: May 2008
    company: Epikoinonia
  ECDL Instructor:
    from: September 2006
    until: June 2007
    company: Webwonders Hellas

projects:
  open source:
    Logs visualizer:
      Source code: https://github.com/arcanoid/logs_visualizer
      Description: A gem that converts a Rails application logs into an image graph, representing all the elements that consisted each action.
      Technologies: Ruby, Graphviz
    Spec producer:
      Source code: https://github.com/arcanoid/logs_visualizer
      Description: A gem that converts a Rails application logs into an image graph, representing all the elements that consisted each action.
      Technologies: Ruby, Rspec
    Multi Cool:
      Source code: https://github.com/arcanoid/multi-cool
      Description: A Rails app that stands as a collection of tools that I frequently search for online, compiled into a single place, such as Sample data generators, JSON, XML beautifiers and more.
      Technologies: RoR
    Json To Ruby Class:
      Source code:  https://github.com/arcanoid/json_to_ruby_class
      Description: A Ruby gem that converts a JSON input to Ruby classes, as well as C# and VB.Net (based on the options passed by the user).
      Technologies: Ruby
    Facts by date:
      Source code: https://github.com/arcanoid/facts_by_date
      Description: A Ruby gem that provides multiple info for specific date, such as events, births and deaths that took place at that specific date.
      Technologies: Ruby
    Random facts:
      Source code: https://github.com/arcanoid/random_facts
      Description: A Ruby gem that allows a user to request random facts with optional parameters such as max size of returned results array.
      Technologies: Ruby
