name: Vasilis Kalligas, Software Engineer
description: The tales of a Software Engineer called Vasilis Kalligas
markdown: kramdown
author: Vasilis Kalligas

gems:
  - jekyll-sitemap

social:
  github: https://github.com/arcanoid
  email: billkall@gmail.com
  google_plus: billkall@gmail.com
  linkedin: https://www.linkedin.com/in/vasileios-kalligas-a7420464

personal_info:
  Date of birth: 24/09/1987
  Residence: Athens, Greece
  Nationality: Greek
  Military obligations: Fulfilled (February 2010 - November 2010)
  Email: billkall@gmail.com
  Phone: (+30) 69432318030

education:
  Athens University of Economics and Business:
    title: Master of Science (MSc), Information systems
    additional_info: Master thesis on "GUI Testing Automation on Android Applications"
    from: 2013
    until: 2015
  Univeristy of Piraeus:
    title: Bachelor's degree, Computer Science
    additional_info: Thesis on "Information Security"
    from: 2005
    until: 2011

languages:
  English: Professional working proficiency
  Greek: Native or bilingual proficiency

hobbies:
  Long walks with my dog: fa fa-paw
  Reading books: fa fa-book
  Grabbing pop-corn and watching a movie at the cinema: fa fa-hand-spock-o
  Hanging out with friends: fa fa-group
  Travelling: fa fa-suitcase

professional_experience:
  Lead Software Engineer @ e-Travel S.A.:
    from: March 2016
    until: now
    company: e-Travel S.A.
  Team Leader for Front-end Team @ e-Travel S.A.:
    from: February 2013
    until: March 2016
    company: e-Travel S.A.
  Web Developer @ e-Travel S.A.:
    from: Novembrer 2011
    until: February 2013
    company: e-Travel S.A.
  Full-stack Software Engineer @ CMS:
    from: March 2011
    until: November 2011
    company: CMS
  Software Engineer @ Wap5 Telecommunications Ltd.:
    from: January 2011
    until: March 2011
    company: Wap5 Telecommunications Ltd.
  ECDL Instructor @ Technoplus:
    from: January 2008
    until: December 2009
    company: Technoplus
  ECDL Instructor @ Epikoinonia:
    from: October 2007
    until: May 2008
    company: Epikoinonia
  ECDL Instructor @ Webwonders Hellas:
    from: September 2006
    until: June 2007
    company: Webwonders Hellas

projects:
  open source:
    Logs visualizer:
      Source code: https://github.com/arcanoid/logs_visualizer
      Description: A gem that converts a Rails application logs into an image graph, representing all the elements that consisted each action.
      Technologies: Ruby, Graphviz
    Spec producer:
      Source code: https://github.com/arcanoid/logs_visualizer
      Description: A gem that converts a Rails application logs into an image graph, representing all the elements that consisted each action.
      Technologies: Ruby, Rspec
    Multi Cool:
      Source code: https://github.com/arcanoid/multi-cool
      Description: A Rails app that stands as a collection of tools that I frequently search for online, compiled into a single place, such as Sample data generators, JSON, XML beautifiers and more.
      Technologies: RoR
    Json To Ruby Class:
      Source code:  https://github.com/arcanoid/json_to_ruby_class
      Description: A Ruby gem that converts a JSON input to Ruby classes, as well as C# and VB.Net (based on the options passed by the user).
      Technologies: Ruby
    Facts by date:
      Source code: https://github.com/arcanoid/facts_by_date
      Description: A Ruby gem that provides multiple info for specific date, such as events, births and deaths that took place at that specific date.
      Technologies: Ruby
    Random facts:
      Source code: https://github.com/arcanoid/random_facts
      Description: A Ruby gem that allows a user to request random facts with optional parameters such as max size of returned results array.
      Technologies: Ruby
